### ISSUE TITLE
Additional Button other then Submit

### ISSUE THREAD

**Issue by SushantVarshney** [DaveWM/ngWizard#10]
I want a extra button at any step and want to call a function from it..

**Comment by DaveWM** [comment]
@SushantVarshney what does this extra button do? Is it something that's applicable for any wizard?

**Comment by SushantVarshney** [comment]
Yeah it can be a sort of additonal functionality that at the completion of
all.the steps in the wizard the user want to save that information not
submitting it.

**Comment by DaveWM** [comment]
In the interests of keeping the api for ngwizard as simple as possible, I think it's best if you do this in your code rather than modifying the wizard. 

Each step in ngwizard is actually a form, so if you wrap your wizard in an `ng-form` you can determine if all the steps have been completed. I've put together [a quick demo](https://plnkr.co/edit/wUMHdAqtd26qej984ggn?p=preview) you can take a look at.
