### ISSUE TITLE
how to get input values in submit method

### ISSUE THREAD

**Issue by orbg** [DaveWM/ngWizard#12]
can you please provide a sample how to get the input values in the submit function in your sample on http://embed.plnkr.co/qj3loQYo4QBjcpEKCcEE/preview 
I can't get it to work for me
Thanks

**Comment by DaveWM** [comment]
See [this example](https://plnkr.co/edit/W0RLp7v8sr6cFALis33Q?p=preview). All you have to do is bind a `$scope` field to the input using `ng-model`. The field needs to contain a dot (this is [best practice for angular](http://learnwebtutorials.com/why-ng-model-value-should-contain-a-dot) anyway), since each `wizard-step` has its own child scope.
